//items

Translation.addTranslation("Grindstone", { ru: "Точильный камень" });
Translation.addTranslation("Tanning machine", { ru: "Растяжка для кожи" });
Translation.addTranslation("Urn", { ru: "Урна" });
Translation.addTranslation("Scarecrow", { ru: "Чучело" });
Translation.addTranslation("Candle", { ru: "Свеча" });
Translation.addTranslation("lampa", { ru: "Фонарь" });
Translation.addTranslation("Chandelier", { ru: "Люстра" });
Translation.addTranslation("Table", { ru: "Стол" });
Translation.addTranslation("Chair", { ru: "Стул" });
Translation.addTranslation("Wardrobe", { ru: "Шкаф" });
Translation.addTranslation("Cup", { ru: "Кружка" });
Translation.addTranslation("Plate", { ru: "Тарелка" });
Translation.addTranslation("Ale", { ru: "Эль" });
Translation.addTranslation("Minor healing", { ru: "Зелье востановления здоровья" });
Translation.addTranslation("Minor magicka", { ru: "Зелье востановления магии" });
Translation.addTranslation("Cheese", { ru: "Сыр" });
Translation.addTranslation("Cabbage", { ru: "Копуста" });
Translation.addTranslation("Green apple", { ru: "Зеленое яблоко" });
Translation.addTranslation("Mammoth snout", { ru: "Хобад мамонта" });
Translation.addTranslation("Sweet roll", { ru: "Сладкий ролл" });
Translation.addTranslation("Tomato", { ru: "Томат" });
Translation.addTranslation("Venison", { ru: "Окорок" });
Translation.addTranslation("Golden coins", { ru: "Золотая монета" });
Translation.addTranslation("Daedra heart", { ru: "Даедрическое сердце" });
Translation.addTranslation("Leather strips", { ru: "Полоски кожи" });
Translation.addTranslation("Corundum ingot", { ru: "Корудиевый слиток" });
Translation.addTranslation("Dwarven metal ingot", { ru: "Cлиток двемерского металла" });
Translation.addTranslation("Ebony ingot", { ru: "Эбонитовый слиток" });
Translation.addTranslation("Malachite ingot", { ru: "Малахитовый слиток" });
Translation.addTranslation("Moonstone ingot", { ru: "Лунный слиток" });
Translation.addTranslation("Orichalcum ingot", { ru: "Орчий слиток" });
Translation.addTranslation("Quicksilver ingot", { ru: "Ртутный слиток" });
Translation.addTranslation("Silver ingot", { ru: "Серебряный слиток" });
Translation.addTranslation("Steel ingot", { ru: "Стальной слиток" });
Translation.addTranslation("Corundum nagget", { ru: "Корудиевый самородок" });
Translation.addTranslation("Dwarven metal nagget", { ru: "Самородок двемерского металла" });
Translation.addTranslation("Ebony nagget", { ru: "Эбонитовый самородок" });
Translation.addTranslation("Malachite nagget", { ru: "Малохитовый самородок" });
Translation.addTranslation("Moonstone nagget", { ru: "Лунный самородок" });
Translation.addTranslation("Orichalcum nagget", { ru: "Орчий самородок" });
Translation.addTranslation("Quicksilver nagget", { ru: "Ртутный самородок" });
Translation.addTranslation("Silver nagget", { ru: "Серебряный самородок" });
Translation.addTranslation("Steel nagget", { ru: "Стальной самородок" });
Translation.addTranslation("Corundum stick", { ru: "Корудиевая палка" });
Translation.addTranslation("Dwarven metal stick", { ru: "Палка из двемерского металла" });
Translation.addTranslation("Ebony stick", { ru: "Эбонитовая палка" });
Translation.addTranslation("Malachite stick", { ru: "Малохитовая палка" });
Translation.addTranslation("Moonstone stick", { ru: "Лунная палка" });
Translation.addTranslation("Orichalcum stick", { ru: "Орчья палка" });
Translation.addTranslation("Quicksilver stick", { ru: "Ртутная палка" });
Translation.addTranslation("Silver stick", { ru: "Стальная палка" });
Translation.addTranslation("Steel stick", { ru: "Стальная палка" });
Translation.addTranslation("Souls stone", { ru: "камень душ" });
